import React from "react";
// import { FaWhatsapp, FaFacebook, FaInstagram, FaTwitter } from "react-icons/fa";
import mahakalLogo from "../assets/mahakal-logo-white.png";
import licenseLogo from "../assets/ssl.png";

// interface SocialLink {
//   href: string;
//   icon: React.ReactNode;
//   ariaLabel: string;
// }

interface FooterLink {
  href: string;
  text: string;
}

// const SOCIAL_LINKS: SocialLink[] = [
//   { href: "https://whatsapp.com/", icon: <FaWhatsapp size={20} />, ariaLabel: "WhatsApp" },
//   { href: "https://facebook.com/", icon: <FaFacebook size={20} />, ariaLabel: "Facebook" },
//   { href: "https://instagram.com/", icon: <FaInstagram size={20} />, ariaLabel: "Instagram" },
//   { href: "https://twitter.com/", icon: <FaTwitter size={20} />, ariaLabel: "Twitter" },
// ];

const FOOTER_LINKS: FooterLink[] = [
  { href: "/privacy", text: "Privacy Policy" },
  { href: "/terms", text: "Terms & Conditions" },
];

// const SocialIcon: React.FC<SocialLink> = ({ href, icon, ariaLabel }) => (
//   <a
//     href={href}
//     className="flex items-center justify-center w-8 h-8 border border-primary-600 text-primary-600 rounded-full transition-all hover:bg-primary-600 hover:text-white"
//     target="_blank"
//     rel="noopener noreferrer"
//     aria-label={ariaLabel}
//   >
//     {icon}
//   </a>
// );

const FooterLink: React.FC<FooterLink> = ({ href, text }) => (
  <a
    href={href}
    className="text-lg text-light transition-all hover:text-primary-600 focus:outline-none focus:ring-2 focus:ring-primary-600 focus:ring-opacity-50"
  >
    {text}
  </a>
);

const LicenseSection: React.FC = () => (
  <div className="bg-success">
    <div className="flex items-center justify-center flex-col md:flex-row gap-5 text-center md:text-left w-full md:w-10/12 lg:w-9/12 xl:w-8/12 mx-auto p-4">
      <div className="w-[99px] h-[74px] shrink-0">
        <img
          src={licenseLogo}
          alt="SSL Security Certificate"
          loading="lazy"
          width={100}
          height={80}
          className="w-full h-full object-contain"
        />
      </div>
      <p className="text-xl font-medium text-secondary-100">
        Players are requested not to contact any untrusted sources for www.Mahakal.com accounts as this is an online site and they can only register independently without any agents. Only deposit through the account details generated by the system or provided by our official support team.
      </p>
    </div>
  </div>
);

const Footer: React.FC = () => {
  return (
    <>
      <footer
        id="footer-section"
        className="py-8 px-4 bg-secondary-200 border-b border-secondary-400"
        role="contentinfo"
      >
        <div className="max-w-[1320px] mx-auto">
          <div className="flex flex-col md:flex-row items-center justify-center md:justify-between gap-7 md:gap-3">
            <div className="w-full md:max-w-[533px] text-center md:text-left">
              <img
                src={mahakalLogo}
                alt="Mahakal Logo"
                loading="lazy"
                width={200}
                height={200}
                className="w-62 h-32 mb-5 mx-auto md:mx-0"
              />
              <p className="text-lg text-neutralGray-700 pl-0 md:pl-6">
                Play casino games, bet on live sports, and get instant betting IDs—all in one secure platform.
              </p>
            </div>
            {/* <div className="text-center md:text-right">
              <p className="text-[22px] leading-8 text-light font-bold mb-4">
                Get in touch
              </p>
              <div className="flex justify-center md:justify-end gap-4">
                {SOCIAL_LINKS.map((link) => (
                  <SocialIcon key={link.ariaLabel} {...link} />
                ))}
              </div>
            </div> */}
          </div>
        </div>

        <div className="mt-8 p-4 bg-secondary-200">
          <div className="max-w-[1320px] mx-auto flex flex-col md:flex-row items-center justify-center gap-4 md:justify-between">
            <div className="flex items-center gap-7 pl-0 md:pl-6">
              {FOOTER_LINKS.map((link) => (
                <FooterLink key={link.href} {...link} />
              ))}
            </div>
            <p className="text-base text-secondary-700">
              © {new Date().getFullYear()} Mahakal. All rights reserved
            </p>
          </div>
        </div>
      </footer>
      <LicenseSection />
    </>
  );
};

export default Footer;
